defaultLevel: DEBUG

categories:
  timer: INFO
  renderer: ERROR

outputs:
  - type: console
    pattern: "[{level}] [{category}] {message}"
  - type: file
    file: "logs/flux.log"
    pattern: "[{time}] [{level}] [{category}] {message}"