defaultLevel: DEBUG

categories:
  timer: INFO
  renderer: ERROR
  opengl: INFO

startupBannerConfig:
  enabled: true
  log-system-info: true

outputs:
  - type: console
    pattern: "[{level}] [{category}] {message}"
  - type: file
    file: "logs/flux.log"
    pattern: "[{time}] [{level}] [{category}] {message}"